/*
 *
 * App constants
 *
 */

export const DEFAULT_ACTION = 'app/App/DEFAULT_ACTION';
export const GET_DATA = 'app/App/GET_DATA';
export const DATA_SUCCESS = 'app/App/DATA_SUCCESS';
export const DATA_ERROR = 'app/App/DATA_ERROR';
export const DISCIPLINES_DATA = 'app/App/DISCIPLINES_DATA';
export const DISCIPLINES_DATA_SUCCESS = 'app/App/DISCIPLINES_DATA_SUCCESS';
export const CLANS_DATA_SUCCESS = 'app/App/CLANS_DATA_SUCCESS';
export const FLAWS_DATA_SUCCESS = 'app/App/FLAWS_DATA_SUCCESS';
export const MERITS_DATA_SUCCESS = 'app/App/MERITS_DATA_SUCCESS';
export const ATTRIBUTE_DATA_SUCCESS = 'app/App/ATTRIBUTES_DATA_SUCCESS';
export const BACKGROUND_DATA_SUCCESS = 'app/App/BACKGROUND_DATA_SUCCESS';
export const SKILLS_DATA_SUCCESS = 'app/App/SKILLS_DATA_SUCCESS';
export const TECHNIQUES_DATA_SUCCESS = 'app/App/TECHNIQUES_DATA_SUCCESS';
export const RITUALS_DATA_SUCCESS = 'app/App/RITUALS_DATA_SUCCESS';
export const CONTENT_PAGES_SUCCESS = 'app/App/CONTENT_PAGES_SUCCESS';
export const YEAR_BOOK_SUCCESS = 'app/App/YEAR_BOOK_SUCCESS';
